Add missing flags and options
WebPlatformForEmbedded/buildroot pull request #446
Opened 2022-06-06 14:05 UTC by lukiwa

software name
software revision
firmware version
audio buffer
video buffer
custom arguments passed to ADK
override persistent directory path
Allow building Morgana as a plugin. 
Formatting fixes
Bump components

2022-06-06 14:13 UTC, sebaszm requested changes

2022-06-06 14:13 UTC, sebaszm commented on package/wpe/wpeframework-disneyplus/wpeframework-disneyplus.mk
> +WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_SOFTWARE_REVISION="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_SOFTWARE_NAME))"
BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_SOFTWARE_NAME

2022-06-07 07:12 UTC, krplata requested changes

2022-06-07 07:12 UTC, krplata commented on package/disney/Config.in
> +    default n
Let's keep this as "on" by default. The same defaults are used for webkit & nf.

2022-06-13 13:22 UTC, merged